vae_name: SimpleVAE
encoder_name: EncoderVAE
decoder_name: DecoderVAE
epochs: 100
batch_size: 32
dropout_keep: 1.0
dropword_keep: 0.62
max_grad: 5.0
vocab_size: 7000
num_sampled_softmax: 100
learning_rate: 0.001
kld_mid: 7
kld_steep: 2
embed_size: 150
latent_variable_size: 50
enc_rnn_size: 200
dec_rnn_size: 200
bow_size: 200
samp_prob: 0.0
rnn_cell: gru
enc_func: mean
len_emb_size: 20
num_len_emb: 300
output_len: 15
max_sentence_length: 20
beam_width: 10
random_seed: 1234
